// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsRK9xWCN-bml0xZS8ibmBpTXyn4k47rk',
    appId: '1:933918553531:web:ed2ff8bc1e5cd0ee40009e',
    messagingSenderId: '933918553531',
    projectId: 'zuri-flow',
    authDomain: 'zuri-flow.firebaseapp.com',
    storageBucket: 'zuri-flow.firebasestorage.app',
    measurementId: 'G-C0WVLKC78Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaazbrnFfykTmMYoXTVEwY1YerapPCUQw',
    appId: '1:933918553531:android:d5cecfcb7f049e8640009e',
    messagingSenderId: '933918553531',
    projectId: 'zuri-flow',
    storageBucket: 'zuri-flow.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1bH3wwEmBNLp9YCZND3Xl6UHLVgIfcBQ',
    appId: '1:933918553531:ios:ede4444bc2fde1eb40009e',
    messagingSenderId: '933918553531',
    projectId: 'zuri-flow',
    storageBucket: 'zuri-flow.firebasestorage.app',
    iosBundleId: 'com.example.zuriProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1bH3wwEmBNLp9YCZND3Xl6UHLVgIfcBQ',
    appId: '1:933918553531:ios:ede4444bc2fde1eb40009e',
    messagingSenderId: '933918553531',
    projectId: 'zuri-flow',
    storageBucket: 'zuri-flow.firebasestorage.app',
    iosBundleId: 'com.example.zuriProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsRK9xWCN-bml0xZS8ibmBpTXyn4k47rk',
    appId: '1:933918553531:web:98769cf3eee0caaf40009e',
    messagingSenderId: '933918553531',
    projectId: 'zuri-flow',
    authDomain: 'zuri-flow.firebaseapp.com',
    storageBucket: 'zuri-flow.firebasestorage.app',
    measurementId: 'G-QVZJVTZMWG',
  );
}
